language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - libsdl1.2-dev
      - libffi-dev
      - python2.7-dev
install:
  - pip install -r requirements.txt
script: python2.7 -m unittest discover
